<template>
  <div class="Cooking">
    <v-row justify="center">
      <v-col cols="12">
        <h1>ตำราอาหาร</h1>
        <v-divider></v-divider>
      </v-col>
    </v-row>
    <v-row justify="center">
      <v-col cols="12">
        <v-responsive>
          <v-card-text
            ><span
              >รายการข้างล่างนี้เป็นตำราทำอาหารนะ
              จะประกอบไปด้วยเครื่องมือที่ใช้ทำ ส่วนผสม และราคาขาย</span
            ></v-card-text
          >
        </v-responsive>
      </v-col>
    </v-row>
    <div v-for="(table, i) in tables" :key="i">
      <v-row>
        <v-col cols="1">
          <v-img width="50px" :src="table[2]"></v-img>
        </v-col>
        <v-col cols="11">
          <h2>{{ table[1] }}</h2>
        </v-col>
      </v-row>

      <v-row justify="center">
        <v-col cols="12">
          <v-simple-table dark>
            <template v-slot:default>
              <thead>
                <tr>
                  <th class="text-center">
                    <h3>อาหาร</h3>
                  </th>
                  <th class="text-left">
                    <h3>ส่วนผสม</h3>
                  </th>
                  <th class="text-left">
                    <h3>0.5 ★</h3>
                  </th>
                  <th class="text-left">
                    <h3>1 ★</h3>
                  </th>
                  <th class="text-left">
                    <h3>1.5 ★</h3>
                  </th>
                  <th class="text-left">
                    <h3>2 ★</h3>
                  </th>
                  <th class="text-left">
                    <h3>2.5 ★</h3>
                  </th>
                  <th class="text-left">
                    <h3>3 ★</h3>
                  </th>
                  <th class="text-left">
                    <h3>3.5 ★</h3>
                  </th>
                  <th class="text-left">
                    <h3>4 ★</h3>
                  </th>
                  <th class="text-left">
                    <h3>4.5 ★</h3>
                  </th>
                  <th class="text-left">
                    <h3>5 ★</h3>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in datafortable(table[0])" :key="item.name">
                  <td class="text-center">
                    <center>
                    <v-img width="6.375rem" :src="item.img"></v-img>
                    </center>
                    {{ item.Recipe }}
                  </td>
                  <td>
                    <span v-for="(ing, i) in item.Ingredients" :key="i">
                      {{ i+1 }}. {{ ing }}
                      <br />
                    </span>
                  </td>
                  <td>{{ item.S05 }}</td>
                  <td>{{ item.S1 }}</td>
                  <td>{{ item.S15 }}</td>
                  <td>{{ item.S2 }}</td>
                  <td>{{ item.S25 }}</td>
                  <td>{{ item.S3 }}</td>
                  <td>{{ item.S35 }}</td>
                  <td>{{ item.S4 }}</td>
                  <td>{{ item.S45 }}</td>
                  <td>{{ item.S5 }}</td>
                </tr>
              </tbody>
            </template>
          </v-simple-table>
        </v-col>
      </v-row>
    </div>
  </div>
</template>

<script>
export default {
  name: "Cooking",
  computed: {},
  data() {
    return {
      tables: [
        ["Stew", "ชุดสตูว์", "https://i.imgur.com/YX0nOCB.png"],
        ["Whisk", "เครื่องตีไข่", "https://i.imgur.com/mQxODft.png"],
        ["Oven", "เตาอบ", "https://i.imgur.com/UaODini.png"],
        ["Cotton", "ไม้นวดแป้ง", "https://i.imgur.com/sTbnGEp.png"],
        ["Frypan", "กระทะ", "https://i.imgur.com/CQ0GUAD.png"],
        ["NoTool", "ไม่ใช้อุปกรณ์", ""],
      ],
      datas: [
        {
          name: "Stew",
          data: [
            {
              img: "https://i.imgur.com/2zrTpt8.png",
              Recipe: "เทมปุระ",
              Ingredients: [
                "ฟักทอง",
                "มะเขือม่วง",
                "เห็ดชิทาเกะ",
                "แป้ง",
                "น้ำมัน",
              ],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/gHMGJnY.png",
              Recipe: "แกงกะหรี่",
              Ingredients: [
                "มันฝรั่ง",
                "หอมใหญ่",
                "ฟักทอง",
                "แครอท",
                "เครื่องเทศ",
              ],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/nj4NQLb.png",
              Recipe: "สตูว์",
              Ingredients: ["มันฝรั่ง", "ดอกกะหล่ำ", "ฟักทอง", "นม"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/laqCY9E.png",
              Recipe: "เฟรนซ์ฟราย",
              Ingredients: ["มันฝรั่ง", "น้ำมัน"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/IdtW889.png",
              Recipe: "ปลาชุบชีสทอด",
              Ingredients: ["ปลาวะคะซะงิ", "แป้ง", "ชีส", "เนย", "น้ำมัน"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/jR7frnJ.png",
              Recipe: "ชิคุเซนนิ",
              Ingredients: ["ถั่ว", "แครอท", "บล็อคโคลิ", "หน่อไม้", "โกโบ้"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/pDh6FIZ.png",
              Recipe: "โอเด้ง",
              Ingredients: ["มันฝรั่ง", "หัวไชเท้า", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/I0r03sp.png",
              Recipe: "พอตอู้เฟือ",
              Ingredients: ["มันฝรั่ง", "แครอท", "บล็อคโคลี่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/gzX0Q89.png",
              Recipe: "ราตาตูย",
              Ingredients: [
                "มันฝรั่ง",
                "มะเขือเทศ",
                "มะเขือม่วง",
                "พริกหยวกเขียว",
              ],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/lP8lHkt.png",
              Recipe: "อจิลโล่",
              Ingredients: [
                "ปลาหมึก",
                "เห็ดหูหนู",
                "เห็ดชิตาเกะ(เล็ก)",
                "เห็ดชิตาเกะ",
                "ปลาหมึกยัก",
              ],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/K06k8i1.png",
              Recipe: "ชาวานมูชิ",
              Ingredients: ["เห็ดชิตาเกะ(เล็ก)", "เห็ดมัทซึตาเกะ", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/HnNdhmX.png",
              Recipe: "ซาโมซา",
              Ingredients: ["มันฝรั่ง", "แป้ง", "น้ำมัน"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/aionNgR.png",
              Recipe: "สตูว์ มังค์ฟิช",
              Ingredients: [
                "หัวไชเท้า",
                "ผักกาดขาว",
                "ปลามังค์ฟิช",
              ],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/NHq2xlH.png",
              Recipe: "ปลาหลน",
              Ingredients: ["โกโบ้", "ปลากะพงแดง", "ขิง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/3HGoAcN.png",
              Recipe: "เยลลี่ ปลาไหล",
              Ingredients: ["ข้าวโพด", "มะเขือเทศ", "ถั่ว", "ปลาไหล"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/MxhXCWO.png",
              Recipe: "เทกิริ",
              Ingredients: [
                "ผักกาดขาว",
                "ปลาปักเป้า",
                "เห็นชีตาเกะ(เล็ก)",
              ],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/ej4G33R.png",
              Recipe: "คอมโพเต้",
              Ingredients: ["ผลโลควอต", "น้ำผึ้ง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/bnDNXnA.png",
              Recipe: "สตูว์ปลาโดะโจ",
              Ingredients: ["ผลโลควอต", "ปลาโดะโจ", "โกโบ้", "หังหอม", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/zX1FuoG.png",
              Recipe: "สตูว์เต่า",
              Ingredients: ["เต่า", "เห็ดชิตาเกะ(เล็ก)", "เห็ดชิตาเกะ"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/9n9jReb.png",
              Recipe: "ปลาราดซอส",
              Ingredients: ["ปลาเทราต์สายรุ้ง", "ขิง", "น้ำผึ้ง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/4127Psi.png",
              Recipe: "กงฟี",
              Ingredients: ["ปลาอายุ", "แตงกวา", "พริกหยวกแดง", "เนย"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/7cmY0eH.png",
              Recipe: "มิโซะแมคาเรล",
              Ingredients: ["ปลาแมคาเรล", "ขิง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/bDwiL7A.png",
              Recipe: "ชุปแป้งทอด",
              Ingredients: ["ปลาวะคะซะงิ", "แป้ง", "น้ำมัน", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/iJhMHVL.png",
              Recipe: "ต้มปลาคาร์บ",
              Ingredients: ["ปลาคาร์บ", "หน่อไม้", "ขิง", "น้ำผึ้ง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/4RuFnEo.png",
              Recipe: "อควา พาซซ่า",
              Ingredients: [
                "ปลาทูแขก",
                "ปลาหมึก",
                "มะเขือเทศ",
                "พริกหยวกเขียว",
                "น้ำมัน",
              ],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/WemvdgB.png",
              Recipe: "ปอแอล",
              Ingredients: ["หัวหอม", "พริกหยวกเขียว", "ปลากระพง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/bTnCSWS.png",
              Recipe: "ปลาฮามาจิต้มไชเท้า",
              Ingredients: ["ปลาฮามาจิ", "หัวไชเท้า"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/V3uaAdc.png",
              Recipe: "S. Turtle Stew",
              Ingredients: ["ปลาไทเกอร์โกไลแอต", "ปลาปิรันย่า", "เครื่องเทศ"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
          ],
        },
        {
          name: "Whisk",
          data: [
            {
              img: "https://i.imgur.com/zae42CX.png",
              Recipe: "นมสตอเบอร์รี่",
              Ingredients: ["สตอเบอรี่", "นม"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/ejnXW6B.png",
              Recipe: "เนย",
              Ingredients: ["นม"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/FJ6RPRu.png",
              Recipe: "มายองเนส",
              Ingredients: ["ไข่", "น้ำมัน"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/cqpzrAJ.png",
              Recipe: "พุดดิ้ง",
              Ingredients: ["นม", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/3OaIEMd.png",
              Recipe: "ซุปเขียว",
              Ingredients: ["ถั่ว", "หัวหอม", "ผักโขม"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/NllAiNr.png",
              Recipe: "ช็อตเค้ก",
              Ingredients: ["สตอเบอรี่", "แป้ง", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/XQU1WPu.png",
              Recipe: "มองบลังค์",
              Ingredients: ["เกาลัด", "เนย", "นม", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
          ],
        },
        {
          name: "Oven",
          data: [
            {
              img: "https://i.imgur.com/pkgX14m.png",
              Recipe: "พายแอปเปิ้ล",
              Ingredients: ["แอปเปิ้ล", "แป้ง", "น้ำผึ้ง", "เนย"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/Jrp1CXP.png",
              Recipe: "ลาซานย่า",
              Ingredients: ["มะเขือเทศ", "บล็อคโคลิ", "แป้ง", "ชีส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/s0braxG.png",
              Recipe: "กราแตง",
              Ingredients: ["ผักกาดขาว", "แป้ง", "ชีส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/AuqmvFY.png",
              Recipe: "คีช",
              Ingredients: ["มันฝรั่ง", "ฟักทอง", "ผักโขม", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/9QwE9Dt.png",
              Recipe: "มันอบ",
              Ingredients: ["มันม่วง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/yffXsmW.png",
              Recipe: "ซุปหอมใหญ่แบบฝรั่งเศส",
              Ingredients: ["หัวหอม", "ชีส", "ขนมปัง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/WGBooVg.png",
              Recipe: "แอปเปิ้ลทาร์ต",
              Ingredients: ["อัลมอนด์", "แอปเปิ้ล", "แป้ง", "เนย"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/34f9gB3.png",
              Recipe: "เค้ก",
              Ingredients: ["อัลมอนด์", "พลัม", "แป้ง", "เนย", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/awEn2Gk.png",
              Recipe: "ปลาอบ",
              Ingredients: ["เชอร์รี่", "ปลาแซลมอน", "เห็ดนาเมโกะ"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/mHb09iG.png",
              Recipe: "ซีฟู้ดอบ",
              Ingredients: ["ปลาฉลามครุย", "ปลามังค์ฟิช", "นางฟ้าทะเล"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
          ],
        },
        {
          name: "Cotton",
          data: [
            {
              img: "https://i.imgur.com/TbXrKTs.png",
              Recipe: "อูด้ง",
              Ingredients: ["ผักโขม", "แป้ง", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/U382TUt.png",
              Recipe: "คุกกี้",
              Ingredients: ["แป้ง", "เนย"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/8z7GvB0.png",
              Recipe: "พิซซ่า",
              Ingredients: ["มะเขือเทศ", "แป้ง", "ชีส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/ZHxEo1d.png",
              Recipe: "ขนมอบ",
              Ingredients: ["แป้ง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/JQ63X5G.png",
              Recipe: "ขนมอบหน้าวอลนัท",
              Ingredients: ["วอลนัท", "แป้ง", "เนย"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/IjVe6Bb.png",
              Recipe: "ขนมอบหน้าจิงจูฉ่าย",
              Ingredients: ["จิงจูฉ่าย", "แป้ง", "เนย"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
          ],
        },
        {
          name: "Frypan",
          data: [
            {
              img: "https://i.imgur.com/rx8kSrg.png",
              Recipe: "ผัดผัก",
              Ingredients: ["กะหล่ำปลี", "หอมใหญ่", "แครอท", "พริกหยวกเขียว"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/pEVmgCg.png",
              Recipe: "พัลบาแช",
              Ingredients: [
                "แครอท",
                "ผักกาดขาว",
                "หน่อไม้",
                "เห็ดชิทาเกะ(เล็ก)",
              ],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/6sUAnO7.png",
              Recipe: "ปาแลร์โม",
              Ingredients: ["หัวหอม", "มะเขือเทศ", "ปลาซาดีน", "ชีส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/StyxaQH.png",
              Recipe: "โอโกโนมิยากิ",
              Ingredients: ["กะหล่ำปลี", "แป้ง", "ไข่", "มายองเนส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/V0lHw5j.png",
              Recipe: "ข้าวโพดอบเนย",
              Ingredients: ["ข้าวโพด", "เนย"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/cnhsI4c.png",
              Recipe: "คาราเมลอัลมอนต์",
              Ingredients: ["อัลมอนต์", "เนย", "เครื่องเทศ"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/WJZW853.png",
              Recipe: "ถั่วอบ",
              Ingredients: ["ถั่ว", "มะเขือเทศ", "แครอท"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/B9iox3W.png",
              Recipe: "แพนเค้ก",
              Ingredients: ["แป้ง", "เนย", "น้ำผึ้ง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/cNc2IU0.png",
              Recipe: "กุ้งทอดซอสพริก",
              Ingredients: ["หัวหอม", "กุ้ง", "เครื่องเทศ"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/p3ksdwS.png",
              Recipe: "สเต็กปลากระโทง",
              Ingredients: ["มันฝรั่ง", "มันม่วง", "ปลากระโทง", "น้ำมัน"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/qtIadOd.png",
              Recipe: "ไข่เจียวปูอัด",
              Ingredients: ["ผักกาดขาว", "ปู", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/uwTNG07.png",
              Recipe: "ไข่ตุ๋น",
              Ingredients: ["หญ้าหางม้า", "ไข่", "รอยัลเฟิร์น"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/1IDIPSE.png",
              Recipe: "ปลาลิ้นหมาทอด",
              Ingredients: ["มะกอก", "ปลาลิ้นหมา", "แป้ง", "เนย"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/y29GBwa.png",
              Recipe: "เอสคาเบช",
              Ingredients: ["แครอท", "หัวหอม", "ปลาคาวาฮากิ", "โยเกิร์ต"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/CrKbkyC.png",
              Recipe: "ทราฟเฟิลไข่",
              Ingredients: ["เห็ดทราฟเฟิล", "ไข่"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/SvVv679.png",
              Recipe: "ซอทีด สลัด",
              Ingredients: [
                "พริกหยวกแดง",
                "บล็อคโคลี่",
                "ปลาดาบ",
                "เครื่องเทศ",
              ],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/8s2gzZp.png",
              Recipe: "เสต็กปลา",
              Ingredients: ["ปลาอะราไพม่า", "ปลาช่อน", "หัวหอม", "มายองเนส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
          ],
        },
        {
          name: "NoTool",
          data: [
            {
              img: "https://i.imgur.com/dC2lR0l.png",
              Recipe: "สลัดฤดูใบไม้ผลิ",
              Ingredients: ["หัวผักกาด", "กะหล่ำปลี", "แตงกวา", "ดอกกะหล่ำ","มายองเนส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/kBXLgK9.png",
              Recipe: "สลัดฤดูร้อน",
              Ingredients: ["มะเขือเทศ", "สัปปะรด", "พริกหยวกแดง", "ข้าวโพด","มายองเนส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/XmGirrf.png",
              Recipe: "สลัดฤดูใบไม้ร่วง",
              Ingredients: ["แครอท", "มันม่วง", "มะเขือม่วง", "พริกหยวกเขียว","มายองเนส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/VgU4rYe.png",
              Recipe: "สลัดฤดูหนาว",
              Ingredients: ["หัวไชเท้า", "ผักกาดขาว", "บล็อคโคลี่","มายองเนส"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/DCLOAmP.png",
              Recipe: "แซนด์วิช",
              Ingredients: ["แตงกวา", "มะเขือเทศ", "ไข่","มายองเนส","ขนมอบ"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/jT0Yhk0.png",
              Recipe: "มันหวาน",
              Ingredients: ["มันม่วง", "นม", "เนย"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/qhLAKOy.png",
              Recipe: "เทอร์รีน",
              Ingredients: ["หัวผักกาด", "กะหล่ำปลี", "แครอท"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/cF25HV2.png",
              Recipe: "บังนา เกาด้า",
              Ingredients: ["แตงกวา", "ฟักทอง", "พริกหยวกแดง","นม"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/oCbAmyi.png",
              Recipe: "นามัสสุ",
              Ingredients: ["แครอท", "หัวไชเท้า"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/nAb0OpF.png",
              Recipe: "ฟรุตสลัด",
              Ingredients: ["สัปปะรด", "แอปเปิ้ล","ส้ม","โยเกิร์ต"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/ToRfOeh.png",
              Recipe: "โดรายากิ",
              Ingredients: ["แป้ง", "ซอสถั่ว"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/HCemQLT.png",
              Recipe: "ทูน่าดอง",
              Ingredients: ["หัวหอม", "ทูน่า","น้ำมัน"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/m0CUJQx.png",
              Recipe: "โยเกิร์ตว่านหางจระเข้",
              Ingredients: ["ว่านหางจระเข้", "โยเกิร์ต","น้ำผึ้ง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/WyxFQ6n.png",
              Recipe: "จี่ปลาโอ",
              Ingredients: ["หัวหอม", "ปลาโอท้องแถบ","ขิง"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/58BSNuk.png",
              Recipe: "ซาชิมิลงเรือ",
              Ingredients: ["ปลากระพงแดง", "ปลาแซลมอน","ปลาโอท้องแถบ","ทูน่า","มะกอก","ปลาลิ้นหมา"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/Qw35kVH.png",
              Recipe: "คาปาชิโอ",
              Ingredients: ["ปลาแซลมอน", "มะเขือเทศ","น้ำมัน"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/LThKChf.png",
              Recipe: "สลัดพลัมแตงกวา",
              Ingredients: ["พลัม", "แตงกวา"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/sCVBAcP.png",
              Recipe: "เทศกาลปลาออร์",
              Ingredients: ["ปลาออร์ยักษ์", "เนย","มอยองเนส","เครื่องเทศ"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
            {
              img: "https://i.imgur.com/5wjknQD.png",
              Recipe: "อาหารแปลก",
              Ingredients: ["หัวผักกาด หรือ แครอท", "มันฝรั่ง หรือ มันม่วง","เห็ดชิตาเกะ(เล็ก)","พลัม หรือ แอปเปิ้ล หรือ ส้ม","กุ้งเครฟิช"],
              S05: "",
              S1: "",
              S15: "",
              S2: "",
              S25: "",
              S3: "",
              S35: "",
              S4: "",
              S45: "",
              S5: "",
            },
          ],
        },
      ],
    };
  },
  methods: {
    datafortable: function(namedata) {
      const result = this.datas.find(({ name }) => name == namedata);
      return result.data;
    },
  },
};
</script>

<style></style>
